services:
  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "api.sls.fi:172.16.2.136"
    image: docker.io/slsfinland/digital_edition_web_ng:latest
    ports:
      - 2089:4201
